/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_granolamatt_hardware_HardwareMemory */

#ifndef _Included_com_granolamatt_hardware_HardwareMemory
#define _Included_com_granolamatt_hardware_HardwareMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_granolamatt_hardware_HardwareMemory
 * Method:    setupIO
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_granolamatt_hardware_HardwareMemory_setupIO
  (JNIEnv *, jclass);

/*
 * Class:     com_granolamatt_hardware_HardwareMemory
 * Method:    setupI2C
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_granolamatt_hardware_HardwareMemory_setupI2C
  (JNIEnv *, jclass);

/*
 * Class:     com_granolamatt_hardware_HardwareMemory
 * Method:    downUser
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_granolamatt_hardware_HardwareMemory_downUser
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
