/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_granolamatt_hardware_HardwareMemory_eResistor */

#ifndef _Included_com_granolamatt_hardware_HardwareMemory_eResistor
#define _Included_com_granolamatt_hardware_HardwareMemory_eResistor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
